webapp/main/models.py
from webapp import db

"""
Модели таблиц базы данных.
Связи в таблицах: "buildings" one-to-many "sections", "tenants" one-to-many "sections"

"""


class Buildings(db.Model):
    __tablename__ = 'buildings'
    id = db.Column(db.Integer, primary_key=True)
    street = db.Column(db.String)
    index = db.Column(db.String, unique=True)
    function = db.Column(db.String)
    count_floors = db.Column(db.Integer)
    sections = db.relationship('Sections', back_populates='building')
    photo = db.Column(db.String)
    lat = db.Column(db.Float)
    lon = db.Column(db.Float)

    def __repr__(self):
        return f"{self.street}, {self.index}"


class Tenants(db.Model):
    __tablename__ = 'tenants'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True)
    email = db.Column(db.String)
    personal_phone = db.Column(db.String)
    commercial_phone = db.Column(db.String)
    start_rent = db.Column(db.Date)
    end_rent = db.Column(db.Date)
    section = db.relationship('Sections', back_populates='tenant')

    def __repr__(self):
        return f"{self.name}"


class Sections(db.Model):
    __tablename__ = 'sections'
    id = db.Column(db.Integer, primary_key=True)
    building_id = db.Column(db.String, db.ForeignKey('buildings.id'))
    index = db.Column(db.Integer)
    floor = db.Column(db.Integer)
    function = db.Column(db.String)
    area = db.Column(db.Float)
    tenant_id = db.Column(db.Integer, db.ForeignKey('tenants.id'))
    tenant = db.relationship('Tenants', back_populates='section')
    building = db.relationship('Buildings', back_populates='sections')

    def __repl__(self):
        return f"{self.index}"

webapp/main/forms.py
from flask_wtf import FlaskForm

from wtforms import EmailField, IntegerField, SelectField, StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email, InputRequired, Length, NumberRange


def check_area(form, field):
    if field.data < form.area_min.data:
        raise ValidationError('Максимальная площадь должна больше минимальной')


class FindSection(FlaskForm):
    func = SelectField(
        'Выбирете назначение помещения - ',
        choices=[('Офис', 'Офис'), ('Производство', 'Производство'), ('Склад', 'Склад')],
    )
    area_min = IntegerField(
        'Минимальная площадь, м²', default=0,
        validators=[InputRequired(),
                    NumberRange(min=0, message='Число не может быть меньше 0')],
    )
    area_max = IntegerField(
        'Максимальная площадь, м²', default=0,
        validators=[InputRequired(),
                    NumberRange(min=0, message='Число не может быть меньше 0'), check_area],
    )
    submit1 = SubmitField('применить')


class FindTenant(FlaskForm):
    name_tenant = StringField(
        'Название компании', id='autocomplete', validators=[DataRequired()], render_kw={"placeholder": "  Поиск"})
    submit2 = SubmitField('Найти')


class ContactForm(FlaskForm):
    name_company = StringField(
        'Компания',
        validators=[DataRequired(),
                    Length(min=2, max=30, message="Поле не может иметь меньше 2х и больше 30ти символов")],
        render_kw={"placeholder": "  Название компании"},
    )
    name_user = StringField(
        'Как мы можем к Вам обращаться',
        validators=[DataRequired(),
                    Length(min=2, max=10, message="Поле не может иметь меньше 2х и больше 10ти символов")],
        render_kw={"placeholder": "  Ф.И.О."},
    )
    email = EmailField(
        "Email",
        validators=[InputRequired("Пожалуйста введите адрес электронной почты"),
                    Email("Пожалуйста введите адрес электронной почты")],
        render_kw={"placeholder": "  Email"},
    )
    phone = StringField(
        'Контактный номер',
        validators=[DataRequired()],
        render_kw={"placeholder": "  Номер телефона"},
    )
    message = StringField(
        'Задать вопрос',
        validators=[DataRequired(),
                    Length(min=1, max=250)],
        render_kw={"placeholder": "  Оставить сообщение"},
    )
    submit3 = SubmitField('Отправить')

webapp/__init__.py
from config import Config

from flask import Flask

from flask_migrate import Migrate

from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    from webapp.main.views import bp as main_bp
    app.register_blueprint(main_bp)
    return app

webapp/main/views.py
from flask import Blueprint, current_app, flash, jsonify, render_template, request

from webapp.main.Message_to_Telegram import send_message_to_telegram
from webapp.main.forms import ContactForm, FindSection, FindTenant
from webapp.main.get_sections import search_sections
from webapp.main.models import Buildings, Tenants

bp = Blueprint('main', __name__)


@bp.route('/', methods=['GET', 'POST'])
def main():
    yandex_api = current_app.config['YANDEX_API_KEY_MAP']
    token = current_app.config['TGBOT_TOKEN']
    chat_id = current_app.config['CHAT_ID']
    find_section_form = FindSection()
    find_tenant_form = FindTenant()
    buildings_data = Buildings.query.all()
    contact_form = ContactForm()
    sections = None
    if request.method == 'POST' and find_section_form.submit1.data:
        if find_section_form.validate():
            func = find_section_form.func.data
            area_min = find_section_form.area_min.data
            area_max = find_section_form.area_max.data
            sections = search_sections(func, area_min, area_max)
        for _, error in find_section_form.errors.items():
            flash(error)
        if not sections:
            flash('Нет свободных помещений по вашему запросу, пожалуйста, свяжитесь с нами, и мы поможем Вам.',
                  category='error')
    tenants = Tenants.query.all()
    tenant = None
    if request.method == 'POST' and find_tenant_form.submit2.data:
        tenant = Tenants.query.filter(Tenants.name == find_tenant_form.name_tenant.data).first()
    if request.method == 'POST' and contact_form.submit3.data:
        callback_application = (f'Компания: {contact_form.name_company.data}\n'
                                f'Имя: {contact_form.name_user.data}\n'
                                f'Почта: {contact_form.email.data}\n'
                                f'Телефон: {contact_form.phone.data}\n'
                                f'Сообщение: {contact_form.message.data}\n')
        send_message_to_telegram(token, chat_id, callback_application)
    return render_template(
        'main.html', yandex_api=yandex_api,
        section_form=find_section_form, tenant_form=find_tenant_form, contact_form=contact_form,
        buildings_data=buildings_data,
        sections=sections, tenant=tenant, tenants=tenants,
    )


@bp.route('/autocomplete', methods=['GET'])
def autocomplete():
    tenants_data = [tenant.name for tenant in Tenants.query.all()]
    return jsonify(json_list=tenants_data)


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('page404.html'), 404

webapp/sections/views.py
from flask import flash, session
from webapp.models import Sections


def search_sections(func, area_min, area_max):         
    sections = Sections.query.order_by(Sections.building_id) \
        .filter(Sections.function == func) \
        .filter(area_max >= Sections.area, Sections.area >= area_min) \
        .filter(Sections.tenant_id.is_(None)) \
        .all()
    if not sections:
        flash('Нет свободных помещений по вашему запросу, пожалуйста, свяжитесь с нами, и мы поможем Вам с выбором.', 
        category='error')
        return 
    return sections

webapp/templates/contact_form.html
<!doctype html>
<html lang="ru">
<body>
  <form method="POST" >
      <div class="form-group">
              <br>
                  {{ form.name_cmpany.label }}
                  {{ form.name_cmpany }}
              <br>
              <br>
                  {{ form.name.label }}
                  {{ form.name }}
              <br>
              <br>
                  {{ form.email.label }}
                  {{ form.email }}
              <br>
              <br>
                  {{ form.phone.label }}
                  {{ form.phone }}
              <br>
              <br>
                  {{ form.message.label }}
                  {{ form.message }}
              <br>
              
              {{ form.submit3 }}
              
              {% with messages = get_flashed_messages() %}
              {% if messages %}
                  <ul class=flashes>
                      {% for message in messages %}
                          {{ message }}
                      {% endfor %}
                  </ul>
              {% endif %}
          {% endwith %}
</body>
</html>                

webapp/templates/contacts/contact_form.html
<form action="{{ url_for('main.main') }}" method="POST">
      <div class="form-group">
              <br>
                  {{ contact_form.name_company.label }}
                  {{ contact_form.name_company }}
              <br>
              <br>
                  {{ contact_form.name_user.label }}
                  {{ contact_form.name_user }}
              <br>
              <br>
                  {{ contact_form.email.label }}
                  {{ contact_form.email }}
              <br>
              <br>
                  {{ contact_form.phone.label }}
                  {{ contact_form.phone }}
              <br>
              <br>
                  {{ contact_form.message.label }}
                  {{ contact_form.message }}
              <br>
              
              {{ contact_form.submit3 }}
              
              {% with messages = get_flashed_messages() %}
              {% if messages %}
                  <ul class=flashes>
                      {% for message in messages %}
                          {{ message }}
                      {% endfor %}
                  </ul>
              {% endif %}
          {% endwith %}
</body>
</html>                

webapp/templates/content/about.html
<section id="about" class="about">
    <div class="container">
        <div class="about__row1-title">
            <div>О проекте</div>
        </div>
        <div class="about__row2-text">
            <div>There are many variations of passages of Lorem Ipsum available, 
                but the majority have suffered alteration in some form, by injected humour, 
                or randomised words which don't look even slightly believable. 
                If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. 
                All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks.
            </div>
        </div>
        <div class="about__row3-navs">
            <div class="about__block">
                <nav class="about__overlap">
                    <a href="#sections" class="nav__link about__nav-text">возможности аренды</a>
                </nav>
            </div>
            <div class="about__block">
                <nav class="about__overlap">
                    <a href="#tenants" class="nav__link about__nav-text">компании на территории</a>
                </nav>
            </div>
        </div>
    </div>
</section>

webapp/templates/content/footer.html
<section id="footer" class="footer">
    <div class="footer__wrapper">
        <div class="footer__block1">
            <div class="footer__block1__contacts">
                <div class="coontacts__headline">
                    Контакты
                </div>
                <div class="coontacts__refs">
                    <a href="#" class="coontacts__ref">
                        <span style="margin-right:20px;"><img src="{{ url_for('static', filename = 'img/frame.svg') }}"/></span>7 922 104 85 16</a><br>
                    <a href="#" class="coontacts__ref">
                        <span style="margin-right:20px;"><img src="{{ url_for('static', filename = 'img/frame1.svg') }}"/></span>livestroy.info@gmail.com</a><br>
                    <a href="#" class="coontacts__ref">
                        <span style="margin-right:20px;"><img src="{{ url_for('static', filename = 'img/frame2.svg') }}"/></span>t.me/livestroy</a><br>
                    <a href="#" class="coontacts__ref">
                        <span style="margin-right:20px;"><img src="{{ url_for('static', filename = 'img/frame3.svg') }}"/></span>Динамовское шоссе, 7</a>
                </div>
                <div class="coontacts__footer">
                    <a href="#" class="coontacts__footer-ref">ООО “ЖилСтрой” 2022 ©</a>
                </div>
            </div>
        </div>
        <div class="footer__block2-yanmap">
            <div id="map" class="map"></div>  
        </div>
    </div>
</section>

webapp/templates/content/header.html
<header class="header">
    <div class="container">
        <div class="header__wrapper">
            <div class="header__block1">
                <a href="/" class="header__logo">
                    <img src="{{ url_for('static', filename = 'img/logo.svg') }}" />
                </a>
            </div>
            <div class="header__block2">
                <nav class="overlap1">
                    <a href="#map-svg" class="nav__link navs-text">карта</a>
                </a>
            </div>
            <div>
                <nav class="overlap1">
                    <a href="#about" class="nav__link navs-text">о проекте</a>
            </div>
            <div class="header__block3">
                <nav class="overlap1">
                    <a href="#footer" class="nav__link navs-text">контакты</a>
                </div>
            </div>
        </div>
        <!-- /header__wrapper -->
    </div>
    <!-- /container -->
</header>

webapp/templates/content/sections.html
<section id="sections" class="sections" style="position:relative">
    <div class="container">

        <div id="rent__block2__apply">
            <a href="#sections" class="contact-form__outer"></a>
            <form action="#rent__block2__applied" method="POST" class="contact-form">
                {{ contact_form.hidden_tag() }}
                <div class="contact-form__title">Заполните форму</div>
                <div class="contact-form__form"> 
                    {{ contact_form.name_company(class_="contact-form__field") }} <br>
                    {{ contact_form.name_user(class_="contact-form__field") }} <br>
                    {{ contact_form.email(class_="contact-form__field") }} <br>
                    {{ contact_form.phone(class_="contact-form__field") }} <br>
                    {{ contact_form.message(class_="contact-form__field") }} <br>
                </div><br>
                <div > 
                    {{ contact_form.submit3(class_="contact-form__submit") }} 
                </div>
            </form>
        </div>
        <div id="rent__block2__applied">
            <a href="#sections" class="contact-form__outer__applied">
                <div class="contact-form__title__applied">Заявка отправилась в обработку</div>
            </a>
        </div>

        <div class="rent__wrapper">
            <div class="rent__block1">
                <div class="rent__block1__row1-headline"><span style="color:#FF7672;">Аренда.</span> 
                    Площади для <br>производства, склада или офиса
                </div>
                
                <div class="rent__block1__row2-text">There are many variations of passages of Lorem Ipsum available, 
                    but the majority have suffered alteration in some form, by injected humour, 
                    or randomised words which don't look even slightly believable. 
                    If you are going to use a passage of Lorem Ipsum, 
                    you need to be sure there isn't anything embarrassing hidden in the middle of text. 
                </div>                  
                
                <form class="rent__block1__row3-wrapper" action= "#sections"  method="POST">
                    {{ section_form.hidden_tag() }}
                    <div class="rent__block1__row3__block1 dropdown">
                        <button class="dropbtn navs-text" disabled>тип помещения  <span><img src="{{ url_for('static', filename = 'img/polygon.svg') }}"/></span></button>
                        <div class="dropdown-content">                                
                            <div>
                                {{ section_form.func(class_="section-form_field") }}
                            </div>
                        </div>
                    </div>
                    <div class="rent__block1__row3__block2 dropdown">
                        <button class="dropbtn navs-text" disabled>площадь  <span><img src="{{ url_for('static', filename = 'img/polygon.svg') }}"/></span></button>
                        <div class="dropdown-content">                                
                            <div>
                                {{ section_form.area_min.label }}
                                {{ section_form.area_min(class_="section-form_field") }}
                            </div>
                            <div>
                                {{ section_form.area_max.label }}
                                {{ section_form.area_max(class_="section-form_field") }}
                            </div>
                        </div>
                    </div>
                    <div class="rent__block1__row3__block3">
                        {{ section_form.submit1(class_="submit-rent-form") }}
                    </div>  
                </form>    

                <div class="rent__block1__row4-results">
                    <div class="rent__results_header">
                        <div>номер здания</div>
                        <div>номер секции</div>
                        <div>тип</div>
                        <div>площадь</div>
                    </div>
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <ul class=flashes>
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% endwith %}
                    {% if sections %}
                    {% for section in sections %}
                    <div class="section-form__results">
                        <div>{{ section.building.index }}</div>
                        <div>{{ section.index }}</div>
                        <div>{{ section.function }}</div>
                        <div>{{ section.area }} м²</div>
                    </div>
                    {% endfor %} 
                    {% endif %}
                </div>
            </div>
            <!-- /rent__block1 -->


            <div class="rent__block2">
                <div class="rent__block2__row1-img">
                    <img src="{{ url_for('static', filename = 'img/section.png') }}"/>
                </div>
                <div class="rent__block2__row2-apply">
                    <button class="rent__apply">
                        <a href="#rent__block2__apply" class="a__text">оставить заявку</a>
                    </button> 
                </div>
            </div>
            <!-- rent__block2 -->
        </div>
    </div>
</section>

webapp/templates/content/tenants.html
<section id="tenants" class="tenants">
    <div class="container">
        <div class="tenants__wrapper">

            <div class="tenants__block1">
                <div class="tenants__block1__row1-img">
                    <img src="{{ url_for('static', filename = 'img/tenant.png') }}"/><img style="position:relative; bottom:220px; left:100px" src="{{ url_for('static', filename = 'img/LOGO2.svg') }}"/>
                </div>
            </div>

            <div class="tenants__block2">
                <div class="tenants__block2__row1-headline">
                    <span style="color:#FF7672;">Компании.</span> 
                    Познакомьтесь <br>с потенциальными соседями <br> вашего помещения
                </div>
                <form class="tenants__block2__row2-wrapper" action= "#tenants"  method="POST">
                    {{ tenant_form.hidden_tag() }}
                    <div class="tenants__block2__row2__block1-searchfield">
                        {{ tenant_form.name_tenant(class_="tenant-form__searchfield") }}
                    </div>
                    <div class="tenants__block2__row2__block2-submit">
                        <div>{{ tenant_form.submit2(class_="tenant-form__submit") }}</div>
                    </div>
                    {% include "scripts/autocomplete_js.html" %}
                </form>
                <div class="tenants__block2__row3-results">    
                    {% if tenant %}
                    <div>
                        <h2>{{ tenant.name }}</h2>
                        {% for section in tenant.section %}
                        <h3>{{ section.index }} - {{ section.building.street }}, {{ section.building.index }}</h3>    
                        {% endfor %}
                    </div>
                    {% else %}
                        {% for tenant in tenants %}
                        <div>
                            <h2>{{ tenant.name }}</h2>
                            {% for section in tenant.section %}
                                <h3>{{ section.index }} - {{ section.building.street }}, {{ section.building.index }}</h3> 
                            {% endfor %}
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

webapp/templates/main.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Жилстрой</title>
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static', filename = 'css/style.css') }}">
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static', filename = 'css/map_style.css') }}">
    {% include "scripts/yandex_map_js.html" %}
    {% include "scripts/autocomplete_ajax.html" %}
</head>
<body>
    {% include "content/header.html" %}
    {% include "content/map.html" %}
    {% include "content/about.html" %}
    {% include "content/sections.html" %}
    {% include "content/tenants.html" %}
    {% include "content/footer.html" %}
</body>
</html>

webapp/templates/maps/js_map.html
<script src="https://api-maps.yandex.ru/2.1/?apikey={{ yandex_api }}&lang=ru_RU" type="text/javascript"></script>
<script text="text/javascript">  
    function init(){
        let map = new ymaps.Map('map', {
            center: [55.06771639944237,60.09706398026949],
            zoom: [17]});
        {% for coordinate in buildings_data %}
        var index = 'mark_' + '{{ coordinate.index }}' 
        var lat = {{ coordinate.lat }}
        var lon = {{ coordinate.lon }}

        index = new ymaps.Placemark([lat, lon])
        map.geoObjects.add(index)
        {% endfor %}
    ;}
    ymaps.ready(init)
    </script> 

webapp/templates/page404.html
<h1>
  Приносим свои извинения.
  Программист, который допустил ошибку будет наказан Флюгегенхайменом.
</h1>  

webapp/templates/scripts/autocomplete_ajax.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>  
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js"></script>  
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css" rel="stylesheet" type="text/css" />

webapp/templates/scripts/autocomplete_js.html
<script>
    $(function() {
        $.ajax({
            url: '{{ url_for("main.autocomplete") }}'
            }).done(function (data) {
                $('#autocomplete').autocomplete({
                    source: data.json_list,
                    minLength: 2
                });
            });
        });
</script>

webapp/templates/scripts/yandex_map_js.html
<script src="https://api-maps.yandex.ru/2.1/?apikey={{ yandex_api }}&lang=ru_RU" type="text/javascript"></script>
<script text="text/javascript">  
    function init(){
        let map = new ymaps.Map('map', {
            center: [55.06771639944237,60.09706398026949],
            zoom: [17]});
        {% for coordinate in buildings_data %}
        var index = 'mark_' + '{{ coordinate.index }}' 
        var lat = {{ coordinate.lat }}
        var lon = {{ coordinate.lon }}

        index = new ymaps.Placemark([lat, lon])
        map.geoObjects.add(index)
        {% endfor %}
    ;}
    ymaps.ready(init)
</script> 

webapp/templates/sections/search_sections.html
<form action= ""  method="POST" >
    <div class="form-group">
    <br>
        {{ form_1.func.label }}
        {{ form_1.func }}
    <br>
    <br>
        {{ form_1.area_min.label }}
        {{ form_1.area_min }}
    <br>
    <br>
        {{ form_1.area_max.label }}
        {{ form_1.area_max }}
    <br>
    {{ form_1.submit }}
</form>      
    <h1> Список свободных помещений </h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    {% if sections != None %}
    {% for section in sections %}
        <h2> Cекция номер - {{ section.index }}, Адрес: {{ section.building.street }} - {{ section.building.index }}  </h2>
        <p> Назначение - {{ section.function }}</p>
        <p> Площадь:{{ section.area }} м^2 </p>
    {% endfor %}  
    {% endif %}      